<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Exsensic.Core\Exsensic.Core.csproj" />
    <ProjectReference Include="..\Exsensic.Data\Exsensic.Data.csproj" />
    <ProjectReference Include="..\Exsensic.Contracts\Exsensic.Contracts.csproj" />
  </ItemGroup>

</Project>
