namespace Exsensic.Web.Models.Shared;

/// <summary>Page title and optional contextual action.</summary>
public sealed class PageHeaderViewModel
{
    /// <summary>The page's primary heading.</summary>
    public required string Title { get; init; }

    /// <summary>Optional supporting explanation.</summary>
    public string? Subtitle { get; init; }

    /// <summary>Optional section label.</summary>
    public string? Eyebrow { get; init; }

    /// <summary>Action label; rendered only with a local URL.</summary>
    public string? ActionText { get; init; }

    /// <summary>Optional local destination generated by the caller.</summary>
    public string? ActionUrl { get; init; }
}
