using System.ComponentModel.DataAnnotations.Schema;
using Exsensic.Contracts.Enums;
using Exsensic.Core.Bookings;
using Exsensic.Core.Bookings.States;

namespace Exsensic.Core.Entities;

/// <summary>
/// The behaviour half of the Booking entity (the properties are in Core/Entities/Booking.cs, owned by Dean).
/// Every status change goes through one of these methods: the current <see cref="BookingState"/> decides
/// whether the action is allowed and what the next status is, and <see cref="Apply"/> is the only place
/// in the system that sets <see cref="Status"/> (docs/CONTRACTS.md §3).
/// </summary>
/// <remarks>
/// Each successful action records a <see cref="BookingStatusChanged"/> event in <see cref="StatusChanges"/>.
/// The booking service hands these to the observers (status history, notifications) before saving, so
/// the history is written in the same transaction as the change. Who may perform an action is checked
/// by the API's authorisation policies before these methods are called.
/// </remarks>
public partial class Booking
{
    /// <summary>The prefix that marks a cancellation as a rejection (docs/CONTRACTS.md §3).</summary>
    public const string RejectionPrefix = "Rejected: ";

    private readonly List<BookingStatusChanged> _statusChanges = [];

    /// <summary>
    /// The events recorded since the booking was loaded or created, oldest first.
    /// Not stored in the database: the observers turn them into history rows and notifications.
    /// </summary>
    [NotMapped]
    public IReadOnlyList<BookingStatusChanged> StatusChanges => _statusChanges;

    /// <summary>The state object for the current status, which decides what is allowed.</summary>
    private BookingState State => BookingState.For(Status);

    /// <summary>
    /// Creates a new booking in Requested status and records the first event. A factory is used instead of
    /// a public constructor so a booking can never start in any other status.
    /// </summary>
    /// <param name="clientUserId">The client making the booking.</param>
    /// <param name="service">The service being booked (already checked to be active).</param>
    /// <param name="timeSlot">The slot being booked (already checked to be available).</param>
    /// <param name="reference">The unique human-readable reference, generated by the booking service.</param>
    /// <param name="nowUtc">The current time, in UTC, from the injected TimeProvider.</param>
    /// <returns>The new booking, not yet saved.</returns>
    public static Booking Create(Guid clientUserId, Service service, TimeSlot timeSlot, string reference, DateTimeOffset nowUtc)
    {
        ArgumentNullException.ThrowIfNull(service);
        ArgumentNullException.ThrowIfNull(timeSlot);
        ArgumentException.ThrowIfNullOrWhiteSpace(reference);

        var booking = new Booking
        {
            ClientUserId = clientUserId,
            Service = service,
            ServiceId = service.Id,
            TimeSlot = timeSlot,
            TimeSlotId = timeSlot.Id,
            Reference = reference,
            Status = BookingStatus.Requested,
            CreatedAtUtc = nowUtc,
            UpdatedAtUtc = nowUtc,
        };

        // The id is 0 until the booking is saved; observers use the booking itself, not this id.
        booking._statusChanges.Add(new BookingStatusChanged(
            booking.Id, BookingAction.Create, FromStatus: null, BookingStatus.Requested, clientUserId, nowUtc, Note: null));

        return booking;
    }

    /// <summary>
    /// An admin approves the booking and assigns a staff member: Requested → Confirmed.
    /// The booking service checks the staff member is qualified and free before calling this.
    /// </summary>
    /// <param name="staffUserId">The staff member to assign.</param>
    /// <param name="adminUserId">The admin approving the booking.</param>
    /// <param name="nowUtc">The current time, in UTC.</param>
    public void Confirm(Guid staffUserId, Guid adminUserId, DateTimeOffset nowUtc)
    {
        var next = State.Confirm();
        if (staffUserId == Guid.Empty)
        {
            throw new ArgumentException("A staff member must be assigned to confirm a booking.", nameof(staffUserId));
        }

        StaffUserId = staffUserId;
        Apply(BookingAction.Confirm, next, adminUserId, nowUtc, note: null);
    }

    /// <summary>
    /// An admin rejects the booking: Requested → Cancelled. The reason is required and is stored with the
    /// "Rejected: " prefix, which is how a rejection is told apart from a cancellation.
    /// </summary>
    /// <param name="reason">Why the booking was rejected, shown to the client.</param>
    /// <param name="adminUserId">The admin rejecting the booking.</param>
    /// <param name="nowUtc">The current time, in UTC.</param>
    public void Reject(string reason, Guid adminUserId, DateTimeOffset nowUtc)
    {
        // The state is asked first, so rejecting a final booking reports invalid_transition, not a missing reason.
        var next = State.Reject();
        if (string.IsNullOrWhiteSpace(reason))
        {
            throw new ArgumentException("A reason is required to reject a booking.", nameof(reason));
        }

        CancellationReason = RejectionPrefix + reason.Trim();
        Apply(BookingAction.Reject, next, adminUserId, nowUtc, CancellationReason);
    }

    /// <summary>
    /// The client or an admin moves the booking to another slot. A Requested booking stays Requested; a
    /// Confirmed booking returns to Requested for re-approval but keeps its proposed staff member, so the
    /// admin can approve the same person again if they are still free.
    /// </summary>
    /// <param name="newTimeSlot">The new slot (already checked to be available by the booking service).</param>
    /// <param name="userId">The client or admin making the change.</param>
    /// <param name="nowUtc">The current time, in UTC.</param>
    public void Reschedule(TimeSlot newTimeSlot, Guid userId, DateTimeOffset nowUtc)
    {
        ArgumentNullException.ThrowIfNull(newTimeSlot);

        var next = State.Reschedule();
        TimeSlot = newTimeSlot;
        TimeSlotId = newTimeSlot.Id;

        var note = $"Moved to {newTimeSlot.SlotDate:yyyy-MM-dd} at {newTimeSlot.StartTime:HH\\:mm}.";
        Apply(BookingAction.Reschedule, next, userId, nowUtc, note);
    }

    /// <summary>
    /// The client or an admin cancels the booking: Requested or Confirmed → Cancelled.
    /// The client cut-off window is checked by the booking service, because admins may cancel at any time.
    /// </summary>
    /// <param name="reason">An optional reason, kept on the booking.</param>
    /// <param name="userId">The client or admin cancelling.</param>
    /// <param name="nowUtc">The current time, in UTC.</param>
    public void Cancel(string? reason, Guid userId, DateTimeOffset nowUtc)
    {
        var next = State.Cancel();

        CancellationReason = string.IsNullOrWhiteSpace(reason) ? null : reason.Trim();
        Apply(BookingAction.Cancel, next, userId, nowUtc, CancellationReason);
    }

    /// <summary>
    /// The assigned staff member or an admin marks the service as delivered: Confirmed → Completed.
    /// Refused before the slot starts.
    /// </summary>
    /// <param name="slotStartUtc">When the booked slot starts, in UTC (slot times are stored in SAST).</param>
    /// <param name="userId">The staff member or admin completing the booking.</param>
    /// <param name="nowUtc">The current time, in UTC.</param>
    public void Complete(DateTimeOffset slotStartUtc, Guid userId, DateTimeOffset nowUtc)
    {
        var next = State.Complete(slotStartUtc, nowUtc);
        Apply(BookingAction.Complete, next, userId, nowUtc, note: null);
    }

    /// <summary>
    /// Sets the new status, updates the timestamp and records the event. The only place Status is changed.
    /// </summary>
    private void Apply(BookingAction action, BookingStatus next, Guid userId, DateTimeOffset nowUtc, string? note)
    {
        var from = Status;
        Status = next;
        UpdatedAtUtc = nowUtc;
        _statusChanges.Add(new BookingStatusChanged(Id, action, from, next, userId, nowUtc, note));
    }
}
